### ISSUE TITLE
Migration to AndroidX

### ISSUE THREAD

**Issue by MonikaJethani** [mozilla/offline-kws-stt-intent-parsing-android#6]
@andrenatal Can I work on migrating this project to AndroidX?

**Comment by andrenatal** [comment]
Hi @MonikaJethani, of course! Just fork it and make a PR whenever you feel ready!

**Comment by MonikaJethani** [comment]
@andrenatal Please review this PR: https://github.com/mozilla/offline-kws-stt-intent-parsing-android/pull/7
